version: '4'

services:
  app:
    build: ./app
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - database

  database:
    image: mariadb
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080