version: '4'

services:
  app:
    build: ./app
    tty: true
    stdin_open: true
    ports:
      - 80:80
    volumes:
      - ./app:/app

  database:
    image: mariadb
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8080:8080